---
#Use § For Color
#use \n For A New Line

#Message When Player it's not In-Game
console-msg: "§7[§cMaskUI!§7] §cBitte Benutze Denn Command In-Game"

#Message When Player Quit The Menu
quit-msg: "§7[§cMaskUI!§7] §eDu Hast Das MaskUI Menu Geschlossen"
...
